cc_library(
    name = "double_array",
    srcs = ["double_array.c"],
    hdrs = ["double_array.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_uthash//:uthash",
    ],
)
