cc_library(
    name = "exit_probability_validator",
    srcs = ["exit_probability_validator.c"],
    hdrs = ["exit_probability_validator.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//common/trinary:trit_array",
        "//consensus/entry_point_selector",
        "//consensus/ledger_validator",
        "//consensus/tangle",
        "//utils:logger_helper",
    ],
)
