cc_test(
    name = "bundle_validator",
    timeout = "moderate",
    srcs = ["bundle_validator.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//ciri/consensus/bundle_validator",
        "//ciri/consensus/test_utils",
        "//common/storage/tests:defs",
        "@unity",
    ],
)
