package(default_visibility = ["//visibility:public"])

cc_library(
    name = "prng",
    srcs = ["prng.c"],
    hdrs = ["prng.h"],
    deps = [
        "//common:errors",
        "//mam/v2:defs",
        "//mam/v2/sponge",
        "//mam/v2/trits",
    ],
)
