package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wots",
    srcs = ["wots.c"],
    hdrs = ["wots.h"],
    deps = [
        "//mam/prng",
        "//mam/sponge",
        "//mam/sponge:spongos",
        "//mam/sponge:spongos_types",
    ],
)
