cc_library(
    name = "pow",
    srcs = ["pow.c"],
    hdrs = ["pow.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common/curl-p:hashcash",
        "//common/trinary:trit_tryte",
    ],
)
