cc_test(name="test_converter",
        srcs=["test_converter.c"],
        deps=[
            "//common/kerl:converter",
            "//common/trinary:trit_tryte",
            "@unity//:unity",
        ])

cc_test(name="test_kerl",
        srcs=["test_kerl.c"],
        deps=[
            "//common/kerl:kerl",
            "//common/trinary:trit_tryte",
            "@unity//:unity",
        ])
