cc_test(
    name = "test_transaction_validator",
    srcs = [
        "test_transaction_validator.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//consensus/snapshot:snapshots_provider",
        "//consensus/test_utils",
        "//consensus/transaction_validator",
        "@unity",
    ],
)
