cc_test(name="test_mam",
        srcs=["test_mam.c"],
        deps=
        [
          "//common/mam:mam",
          "//common/trinary:trit_tryte",
          "@unity//:unity",
        ])

cc_test(name="test_mask",
        srcs=["test_mask.c"],
        deps=
        [
          "//common/mam:mask",
          "//common/trinary:trit_tryte",
          "@unity//:unity",
        ])

cc_test(name="test_merkle",
        srcs=["test_merkle.c"],
        deps=
        [
          "//common/mam:merkle",
          "//common/trinary:trit_tryte",
          "@unity//:unity",
        ])
