cc_library(
    name = "collector",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    include_prefix = "iota/tanglescope/collector",
    visibility = ["//visibility:public"],
    deps = ["@yaml_cpp"],
)
