cc_library(
    name = "requests",
    srcs = glob([
        "*.h",
        "*.c",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    include_prefix = "request",
    visibility = ["//visibility:public"],
    deps = [
        "//cclient/types",
    ],
)
