/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iota_mobile_Interface */

#ifndef _Included_org_iota_mobile_Interface
#define _Included_org_iota_mobile_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iota_mobile_Interface
 * Method:    doPOW
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_iota_mobile_Interface_doPOW
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
