cc_test(
    name = "test_http",
    timeout = "short",
    srcs = [
        "test_http.c",
    ],
    flaky = True,
    deps = [
        "//cclient/http",
        "@cJSON",
        "@unity",
    ],
)
