#ifndef __COMMON_CURL_P_PEARL_DIVER_H_
#define __COMMON_CURL_P_PEARL_DIVER_H_

typedef enum {
  PEARL_DIVER_SUCCESS,
  PEARL_DIVER_RUNNING,
  PEARL_DIVER_INTERRUPTED,
  PEARL_DIVER_ERROR
} PearlDiverStatus;

#endif
