#include <stdio.h>
#include <unity/unity.h>

#include "common/curl-p/trit.h"
#include "common/trinary/trit_tryte.h"
#include "common/sign/iss_curl.h"

#define TEST_SEED                                                              \
  "ABCDEFGHIJKLMNOPQRSTUVWXYZ9ABCDEFGHIJKLMNOPQRSTUVWXYZ9ABCDEFGHIJKLMNOPQRST" \
  "UVWXYZ9"
#define EXPECT_SUBSEED                                                         \
  "HUZQQZYTQCPXWJKLMWDOGC9FLWEGPFZNWJSGXSDKYDIUGUBKGAKXSLHVBYBTENFHDUWJSTKIUZ" \
  "WLWHOZX"

void test_subseed(trit_t *seed, trit_t *subseed, int64_t i, Curl *curl) {
  tryte_t tryte_seed[] = TEST_SEED;
  trytes_to_trits(tryte_seed, seed, 81);

  iss_curl_subseed(seed, subseed, i, curl);

  trits_to_trytes(subseed, tryte_seed, HASH_LENGTH);
  TEST_ASSERT_EQUAL_MEMORY(EXPECT_SUBSEED, tryte_seed, strlen(EXPECT_SUBSEED));
}
#undef EXPECT_SUBSEED
#undef TEST_SEED

#define EXP_KEY                                                                \
  "HQBY9H99LL9ERVHWKJCOREFUTHHGRWTWL9LHWWPNGICORKCAVC9LOHLMHZSNDPWXGEJIYMZXWS" \
  "HJOITHKVAQUPBQLSHECPJPNBCBQCORDUFIXADZKOPKJISUJIF9KGTTFM9EKAPAFRBBHEA9YFFI" \
  "NPXGJURMVXMSXTOTKNQNO9XYBQRXCGBWEC9RFZMMDBGR9PYVGYXPVDHFZNPF9M9DHYYPDHMZOU" \
  "CVFJTYT9YH9PPKTXSBRKKQHHRRTPXSEHNVIUTISPHAFMEJP9ZYZWBCSSBZKTSKBUSWZIRWGHFE" \
  "AAJIGMGMDXCIZBWZVQXMKLBDMYQMOA9BQFZWDPEVHYR9LIMD9RXLBBJQJOREFHAIBAHZAFRUEC" \
  "KAVQTV9YJEJYZYRFJULGEEHNQTW9AFYLIOHNRWLKHVDZELUSIMTNPCNMRRNUKCNAKSHTULCUPK" \
  "ATKLUHKQKTJXFHXIGODJDUWPVHCIRLOAJYRHTGRKYLNWAARWMQGUZPDOSZYKYZFGY9XYNGYU9O" \
  "9WBTWGTDAJEXRVBBBRUHASMHSXLFIOLVYIO9PACQUTRCXSCXULJSXUMZZ9YYGAA9ULWRMMJZSJ" \
  "RKBDWEMSZIBOX9DNHXGETPEGYUAPCKAI9BZUC9WR9KVI9DYDCBDLZUTXKWHXTJVRQJQQJI99MS" \
  "KQWKOYKANXLWHLLZG9T9OANTQUXVCQTBIII9SPEJWWRLTTFNELLDPDYSHTTYXQFMEIVMNHNHJW" \
  "GQVKQJEWZCCWNNXFAVWGBHMPHJAEFCK9AJLORCWBXFPQSHEPPBISQTOLOQERJFFHMMRTXJFPBH" \
  "Y9CZVQQVDVLTBLNPIFQTRGVKNCBDLCFLNWCGLEYEMIUBSBTBHDVHNZNBXKFXABDUWILZNFGPQL" \
  "IKGTLGKLFBVIXJMPULNUDKACXCIMMHWLUUG9DPHSGUWQICZYDJMZKKIUSFXUCQTKIRZVJYHZAQ" \
  "HKPKCFHEUYJRXDRFRIVZJPJSXD9YMZSSCKZTKFEEOQQJRQPLKLTIWGRU9EU9WYJEODVHQOBWDH" \
  "EEUOVAFYEGAFKUJKDGROHQCOSNSAHTTBXNRISCXPGCWXDMIHZPUXXTYOKTVFNTOGKDSAJAWJPY" \
  "UGVACZ9AZEIC9FBKVIYGCWPQKHZJXN9BOZQAPCXXHNRXFGMQCHRUAUAAIXDEXRRXMVCYM9VENK" \
  "HAMFFAMNPTFSLDPKSYBTALNCGGZNZQZDWXNXSBGRUWYZRGP9PNFGIMAVYJGYDATLSTPYVBYAQZ" \
  "BYQXSAVHWPSBZTEMESUVVJQPGKDGHSFRDINFMUKGOHGNHKEOFLRBGBNHNFKZOVJCLDWIXBDWCO" \
  "RBNYPZVFVGIXZGHOMUKJPFOFMJDJN9CFN9DSPBCVUPMIZDCKXXHIJIDMQSGXWVRHIOATTQAKHE" \
  "UDKSFHJWFMQDNKMAJJFOUUPACRPLUQGWWRBLWH9HTQPWWGVSRCQARKEIFCELAAOQBWNYRUCDBI" \
  "Q9FUTFTDZGLXDIGUHGFOMYNLNRCRH9QNREAIFUWXQ9GKW9BFBIQFQANSGG9DFDN9IPTXYSINYX" \
  "BHDCMAZLYOGILTXHGLRGJPHU9EPINZCOVMJJBYFHRPPXUFHMFFTKAZGCJDSCUFULARWDAWQJDU" \
  "JVIPRZIFLDIDYXXXPVGPEEAMOUDJOMTELJODRRFL9VIX99LEFAGRBUOUWHMQGBJBFJEQPLNGVK" \
  "SDLIYDAIXZBIWLKZVPKSNXQOGBDFZATKRDQWT9NSVXUZGBJAUBSI9XDMVVBGNSMRDADMRVNODY" \
  "YCQLEJWXXIHVKHKCHPTQYZQXPZGXYBYHNWLFBFYHCSWEBCRGWZ9FFOJFYZIGPYUVKWUIQPSWVM" \
  "OEF9TFRNQDFPDQFUMCKZVAOLYMOUILKETPURIYFAHSSKRNITYOHEQ9A9DDJYTQUMHOEJ9HHUY9" \
  "NOMNSSENHFSQMYCDWKOI9VEEYEDYGH9DDDOZOEZOHIKIRCROAGSBY9CVDK9OHWGRKIFOWWPTOG" \
  "XTXKWJRRIP9APBZLLFE9YQENGRXCBSOXWRHFGEMTXTGJUXSNNZKEWEWP9FMXQERRHNNHAYMLZP" \
  "OHQGLIKNBJZPRQFQLAIOOQDUZGVCDIDCGAWHNAXZKLT9GQQKEKXLBEORGZIPXLRBUJRHGGJZRB" \
  "JPLC9VLGJFTVUHPWCBYZCOFTV9SMVFVDGQPJMQLKK"
void test_key(trit_t *s, trit_t *k, size_t l, Curl *c) {
  iss_curl_key(s, k, l, c);
  tryte_t k_t[l];

  trits_to_trytes(k, k_t, l);

  TEST_ASSERT_EQUAL_MEMORY(EXP_KEY, k_t, l / 3 * sizeof(tryte_t));
}
#undef EXP_KEY

#define EXP_ADDY                                                               \
  "DKAKEXFTGNTZSFGQBGHTHQHGMJCRTAVUTCDGEABKAMTNRXMQINGPSKCKOUBUFJFKRVDKGKNIMT" \
  "WYWDRDS"

void test_addy(trit_t *k, size_t l, Curl *c) {
  tryte_t addy_trytes[l];

  iss_curl_key_digest(k, k, l, c);
  iss_curl_address(k, k, c);

  trits_to_trytes(k, addy_trytes, l);

  addy_trytes[HASH_LENGTH / 3] = 0;

  TEST_ASSERT_EQUAL_MEMORY(EXP_ADDY, addy_trytes,
                           HASH_LENGTH / 3 * sizeof(tryte_t));
}
#undef EXP_ADDY

void test_iss() {
  trit_t seed[HASH_LENGTH];
  trit_t subseed[HASH_LENGTH];
  trit_t key[ISS_KEY_LENGTH];
  int64_t index = 3;
  size_t key_length = ISS_KEY_LENGTH;

  Curl curl;
  curl.type = CURL_P_81;
  init_curl(&curl);

  test_subseed(seed, subseed, index, &curl);
  test_key(subseed, key, key_length, &curl);
  test_addy(key, key_length, &curl);
  // printf("%s\n", addy_trytes);
}

int main(void) {
  UNITY_BEGIN();

  RUN_TEST(test_iss);
  // RUN_TEST(test_curl_p_81_works);
  // RUN_TEST(test_other);

  return UNITY_END();
}
