cc_test(
    name = "test_iss_curl",
    srcs = [
        "test_iss_curl.c",
    ],
    deps = [
        "//common/curl-p:trit",
        "//common/sign/v2:iss_curl",
        "//common/trinary:trit_tryte",
        "@unity",
    ],
)
