package(default_visibility = ["//visibility:public"])

cc_library(
    name = "normalize",
    srcs = ["normalize.c"],
    hdrs = ["normalize.h"],
    deps = [
        "//common/trinary:flex_trit",
        "//common/trinary:trit_long",
        "//common:defs",
    ],
)
