package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mss",
    srcs = ["mss.c"],
    hdrs = ["mss.h"],
    deps = [
        "//common:errors",
        "//mam/v2:alloc",
        "//mam/v2/wots",
    ],
)
