/*
 * Copyright (c) 2018 IOTA Stiftung
 * https://github.com/iotaledger/entangled
 *
 * Refer to the LICENSE file for licensing information
 */

#include <unity/unity.h>

#include "utils/containers/lists/concurrent_list.c.inc"
#include "utils/containers/lists/concurrent_list.h.inc"

DECLARE_CL(int)
DEFINE_CL(int)

static bool int_cmp(int const *const a, int const *const b) { return *a == *b; }

void test_list() {
  int data;
  concurrent_list_int *list = NULL;
  concurrent_list_int *nlist = NULL;

  TEST_ASSERT_EQUAL_INT(CL_INIT(int, list, int_cmp), CL_SUCCESS);
  TEST_ASSERT_NOT_NULL(list);

  TEST_ASSERT_NULL(list->vtable->front(NULL));
  TEST_ASSERT_NULL(CL_FRONT(list));
  TEST_ASSERT_NULL(list->vtable->back(NULL));
  TEST_ASSERT_NULL(CL_BACK(list));
  TEST_ASSERT_EQUAL_INT(list->vtable->empty(NULL), true);
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), true);
  TEST_ASSERT_EQUAL_INT(list->vtable->size(NULL), 0);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 0);

  TEST_ASSERT_EQUAL_INT(list->vtable->push_front(NULL, 42), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 42), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 42);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 42);
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 1);
  TEST_ASSERT_EQUAL_INT(list->vtable->pop_front(NULL, &data), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_POP_FRONT(list, NULL), CL_NULL_DATA);
  TEST_ASSERT_EQUAL_INT(CL_POP_FRONT(list, &data), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(data, 42);
  TEST_ASSERT_NULL(CL_FRONT(list));
  TEST_ASSERT_NULL(CL_BACK(list));
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), true);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 0);
  TEST_ASSERT_EQUAL_INT(CL_POP_FRONT(list, &data), CL_EMPTY);

  TEST_ASSERT_EQUAL_INT(list->vtable->push_back(NULL, 42), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 42), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 42);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 42);
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 1);
  TEST_ASSERT_EQUAL_INT(list->vtable->pop_back(NULL, &data), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_POP_BACK(list, NULL), CL_NULL_DATA);
  TEST_ASSERT_EQUAL_INT(CL_POP_BACK(list, &data), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(data, 42);
  TEST_ASSERT_NULL(CL_BACK(list));
  TEST_ASSERT_NULL(CL_FRONT(list));
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), true);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 0);
  TEST_ASSERT_EQUAL_INT(CL_POP_BACK(list, &data), CL_EMPTY);

  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 0), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 1), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 2), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 3), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 4), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 5), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 6), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 7), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_FRONT(list, 8), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_PUSH_BACK(list, 9), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 10);
  concurrent_list_node_int *tmp = list->front;
  TEST_ASSERT_NOT_NULL(tmp);
  TEST_ASSERT_EQUAL_INT(tmp->data, 8);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 6);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 4);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 2);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 0);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 1);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 3);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 5);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 7);
  tmp = tmp->next;
  TEST_ASSERT_EQUAL_INT(tmp->data, 9);
  tmp = tmp->next;
  TEST_ASSERT_NULL(tmp);

  TEST_ASSERT_NULL(list->vtable->find(NULL, 0));
  TEST_ASSERT_EQUAL_INT(list->vtable->contains(NULL, 0), false);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 0), 0);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 0), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 1), 1);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 1), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 2), 2);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 2), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 3), 3);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 3), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 4), 4);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 4), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 5), 5);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 5), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 6), 6);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 6), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 7), 7);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 7), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 8), 8);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 8), true);
  TEST_ASSERT_EQUAL_INT(*CL_FIND(list, 9), 9);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 9), true);
  TEST_ASSERT_NULL(CL_FIND(list, 10));
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 10), false);
  TEST_ASSERT_NULL(CL_FIND(list, 42));
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 42), false);
  TEST_ASSERT_NULL(CL_FIND(list, -1));
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, -1), false);

  TEST_ASSERT_EQUAL_INT(list->vtable->remove(NULL, 0), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 8), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 8), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 9);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 9);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 9), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 9), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 8);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 7);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 0), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 0), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 7);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 7);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 4), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 4), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 7);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 5), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 5), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 5);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 6);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 7);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 6), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 6), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 4);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 2);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 7);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 7), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 7), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 3);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 2);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 3);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 1), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 1), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 2);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 2);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 3);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 2), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 2), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 1);
  TEST_ASSERT_EQUAL_INT(*CL_FRONT(list), 3);
  TEST_ASSERT_EQUAL_INT(*CL_BACK(list), 3);
  TEST_ASSERT_EQUAL_INT(CL_REMOVE(list, 3), CL_SUCCESS);
  TEST_ASSERT_EQUAL_INT(CL_CONTAINS(list, 3), false);
  TEST_ASSERT_EQUAL_INT(CL_SIZE(list), 0);
  TEST_ASSERT_EQUAL_INT(CL_EMPTY(list), true);
  TEST_ASSERT_NULL(CL_FRONT(list));
  TEST_ASSERT_NULL(CL_BACK(list));

  TEST_ASSERT_EQUAL_INT(CL_DESTROY(int, nlist), CL_NULL_SELF);
  TEST_ASSERT_EQUAL_INT(CL_DESTROY(int, list), CL_SUCCESS);
  TEST_ASSERT_NULL(list);
}

int main(void) {
  UNITY_BEGIN();

  RUN_TEST(test_list);

  return UNITY_END();
}
