cc_library(
    name='collector',
    include_prefix='iota/utils/collector',
    hdrs=glob(['*.hpp']),
    srcs=glob(['*.cpp']),
    deps=['@yaml_cpp//:yaml_cpp'],
    visibility=['//visibility:public'])