package(default_visibility = ["//visibility:public"])

cc_library(
    name = "troika",
    srcs = ["troika.c"],
    hdrs = ["troika.h"],
    deps = [
        "//common:stdint",
        "//common/trinary:trits",
        "//common/trinary:tryte",
    ],
)
