cc_test(
    name = "test_sponge",
    timeout = "short",
    srcs = ["test_sponge.c"],
    deps = [
        "//mam/sponge",
        "@unity",
    ],
)

cc_test(
    name = "test_spongos",
    timeout = "short",
    srcs = ["test_spongos.c"],
    deps = [
        "//mam/sponge:spongos",
        "//mam/sponge:spongos_types",
        "@unity",
    ],
)
