cc_test(
    name = "test_prng",
    srcs = ["test_prng.c"],
    deps = [
        "//mam/v2/prng",
        "//mam/v2/test_utils",
        "@unity",
    ],
)

cc_test(
    name = "test_prng_types",
    srcs = ["test_prng_types.c"],
    deps = [
        "//mam/v2/prng",
        "//mam/v2/prng:mam_prng_t_set",
        "//mam/v2/prng:prng_types",
        "@unity",
    ],
)
