cc_test(
    name = "test_prng",
    srcs = ["test_prng.c"],
    visibility = ["//visibility:private"],
    deps = [
        "//common/trinary:trit_tryte",
        "//mam/prng",
        "@unity",
    ],
)
