cc_test (
    name = "test_transaction",
    srcs = ["test_transaction.c"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:transaction",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_transaction_3",
    srcs = ["test_transaction.c"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:transaction_3",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_transaction_4",
    srcs = ["test_transaction.c"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:transaction_4",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_transaction_5",
    srcs = ["test_transaction.c"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:transaction_5",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_tryte_transaction",
    srcs = ["test_tryte_transaction.cc"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:tryte_transaction",
        "@com_google_googletest//:gtest_main",
        ]
)

cc_test (
    name = "test_tryte_transaction_3",
    srcs = ["test_tryte_transaction.cc"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:tryte_transaction_3",
        "@com_google_googletest//:gtest_main",
        ]
)

cc_test (
    name = "test_tryte_transaction_4",
    srcs = ["test_tryte_transaction.cc"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:tryte_transaction_4",
        "@com_google_googletest//:gtest_main",
        ]
)

cc_test (
    name = "test_tryte_transaction_5",
    srcs = ["test_tryte_transaction.cc"],
    deps = [
        "//common/trinary:trit_tryte",
        "//common/model:tryte_transaction_5",
        "@com_google_googletest//:gtest_main",
        ]
)
