cc_test(
    name = "test_mss",
    timeout = "eternal",
    srcs = ["test_mss.c"],
    deps = [
        "//mam/mss",
        "//mam/test_utils",
        "//utils/handles:rand",
        "@unity",
    ],
)
