cc_test(
    name = "test_mss_classic",
    timeout = "eternal",
    srcs = ["test_mss.c"],
    deps = [
        "//mam/mss:mss_classic",
        "//utils/handles:rand",
        "@unity",
    ],
)

cc_test(
    name = "test_mss_traversal",
    timeout = "eternal",
    srcs = ["test_mss.c"],
    deps = [
        "//mam/mss:mss_traversal",
        "//utils/handles:rand",
        "@unity",
    ],
)
