steps:
  - name: "bazel test opt"
    command: bazel test -c opt --test_output=all //...
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
  - name: "bazel test debug"
    command: bazel test -c dbg --test_output=all //...
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
  - name: "bazel test bootlin x86_64 toolchains"
    command: bazel build --crosstool_top=@iota_toolchains//tools/x86-64-core-i7--glibc--bleeding-edge-2018.07-1:toolchain --cpu=i686 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  //...
    plugins:
      docker#v1.3.0:
        image: "th0br0/iota-buildenv:x86_64"
        mounts:
          - /conf:/conf
