cc_test(
    name = "test_api",
    timeout = "long",
    srcs = ["test_api.c"],
    deps = [
        "//common/trinary:tryte_ascii",
        "//mam/v2/api",
        "//mam/v2/test_utils",
        "@unity",
    ],
)
