package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wallet",
    srcs = ["wallet.c"],
    hdrs = ["wallet.h"],
    deps = [
        "//common:errors",
        "//mam/v2/mam:mam_pre_shared_key_t_set",
        "//mam/v2/mam:mam_types",
    ],
)
