package(default_visibility = ["//visibility:public"])

cc_library(
    name = "transaction",
    srcs = ["transaction.c"],
    hdrs = ["transaction.h"],
    deps = [
        "//common/trinary:tryte_long",
    ],
)
