cc_library(
    name = "tipselection",
    srcs = ["tipselection.c"],
    hdrs = ["tipselection.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//common/trinary:trit_array",
        "//consensus:structs",
        "//consensus/cw_rating_calculator",
        "//consensus/entry_point_selector",
        "//consensus/ledger_validator",
        "//consensus/milestone",
        "//consensus/view_models",
        "//consensus/walker",
        "//consensus/walker_validator",
        "//utils:logger_helper",
    ],
)
