package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sponge",
    srcs = ["sponge.c"],
    hdrs = ["sponge.h"],
    deps = [
        "//common:errors",
        "//common/crypto/curl-p:trit",
        "//common/crypto/kerl",
        "//common/trinary:flex_trit",
    ],
)
