cc_test(
    name = "test_tangle",
    timeout = "moderate",
    srcs = ["test_tangle.c"],
    deps = [
        "//ciri/consensus/tangle",
        "//ciri/consensus/test_utils",
        "@unity",
    ],
)
