cc_library(
    name = "prng",
    srcs = ["prng.c"],
    hdrs = ["prng.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//mam:defs",
        "//mam/pb3",
        "//mam/sponge",
        "//mam/trits",
        "//utils:memset_safe",
    ],
)
