cc_test(
    name = "test_psk",
    timeout = "short",
    srcs = ["test_psk.c"],
    visibility = ["//visibility:private"],
    deps = [
        "//common/trinary:trit_tryte",
        "//mam/psk",
        "//mam/psk:mam_psk_t_set",
        "@unity",
    ],
)
