cc_test(
    name = "test_get_node_info",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_node_info.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_find_transactions",
    timeout = "moderate",
    srcs = [
        "cclient_conf.h",
        "test_find_transactions.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_check_consistency",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_check_consistency.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_balances",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_balances.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_inclusion_states",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_inclusion_states.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_tips",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_tips.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_trytes",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_trytes.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_were_addresses_spent_from",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_were_addresses_spent_from.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_attach_to_tangle",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_attach_to_tangle.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_add_neighbors",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_add_neighbors.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_broadcast_transactions",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_broadcast_transactions.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_neighbors",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_neighbors.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_remove_neighbors",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_remove_neighbors.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_store_transactions",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_store_transactions.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_transactions_to_approve",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_transactions_to_approve.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)
