cc_test(
    name = "test_get_node_info",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_node_info.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_find_transactions",
    timeout = "moderate",
    srcs = [
        "cclient_conf.h",
        "test_find_transactions.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_check_consistency",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_check_consistency.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_balances",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_balances.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)

cc_test(
    name = "test_get_inclusion_states",
    timeout = "short",
    srcs = [
        "cclient_conf.h",
        "test_get_inclusion_states.c",
    ],
    deps = [
        "//cclient/api",
        "@unity",
    ],
)
