cc_test(
    name = "test_entry_point_selector",
    timeout = "moderate",
    srcs = ["test_entry_point_selector.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//ciri/consensus/test_utils",
        "//ciri/consensus/tip_selection/entry_point_selector",
        "//ciri/utils:files",
        "//common/helpers:digest",
        "//common/model/tests:defs",
        "@unity",
    ],
)
