cc_library(
    name = "milestone_tracker",
    srcs = ["milestone_tracker.c"],
    hdrs = ["milestone_tracker.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//utils:logger_helper",
        "//utils/handles:thread",
    ],
)
