cc_binary(
    name = "send",
    srcs = ["send.c"],
    deps = [
        "//cclient:api",
        "//mam/v2/api",
    ],
)

cc_binary(
    name = "recv",
    srcs = ["recv.c"],
    deps = [
        "//cclient:api",
        "//mam/v2/api",
    ],
)
