cc_library(
    name = "responses",
    srcs = glob([
        "*.c",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//cclient/types",
        "//utils:char_buffer",
    ],
)
