cc_library(
    name = "responses",
    srcs = glob([
        "*.c",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//utils:char_buffer",
        "//utils/containers/hash:hash243_queue",
        "//utils/containers/hash:hash243_stack",
        "//utils/containers/hash:hash8019_queue",
        "//utils/containers/hash:hash_array",
    ],
)
