load(":hash_container_generator.bzl", "hash_container_generate")

# Sets

hash_container_generate(
    size = 27,
    type = "set",
)

hash_container_generate(
    size = 81,
    type = "set",
)

hash_container_generate(
    size = 243,
    type = "set",
)

hash_container_generate(
    size = 6561,
    type = "set",
)

hash_container_generate(
    size = 8019,
    type = "set",
)
