cc_test(
    name = "test_ftroika",
    timeout = "moderate",
    srcs = ["test_ftroika.c"],
    deps = [
        "//common/crypto/ftroika",
        "//common/crypto/troika",
        "@unity",
    ],
)
