cc_library(
    name = "entry_point_selector",
    srcs = ["entry_point_selector.c"],
    hdrs = ["entry_point_selector.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//consensus/milestone_tracker",
        "//utils:macros",
    ],
)
