cc_library(
    name = "entry_point_selector",
    srcs = ["entry_point_selector.c"],
    hdrs = ["entry_point_selector.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//common/trinary:trit_array",
        "//consensus/milestone",
        "//consensus/tangle",
        "//consensus/view_models",
        "//utils:logger_helper",
    ],
)
