NODE_MAINNET_VARIABLES = [
    "MWM=14",
    "COORDINATOR_ADDRESS='\"EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9\"'",
]

NODE_TESTNET_VARIABLES = [
    "MWM=9",
    "COORDINATOR_ADDRESS='\"EQQFCZBIHRHWPXKMTOLMYUYPCN9XLMJPYZVFJSAY9FQHCCLWTOLLUGKKMXYFDBOOYFBLBI9WUEILGECYM\"'",
]
