package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_utils",
    srcs = ["test_utils.c"],
    hdrs = ["test_utils.h"],
    deps = [
        "//mam/mss",
        "//mam/ntru",
        "//mam/ntru:poly",
        "//mam/prng",
        "//mam/sponge",
        "//mam/sponge:spongos",
        "//mam/wots",
    ],
)
