package(default_visibility = ["//visibility:public"])

cc_library(
    name = "configuration",
    hdrs = ["configuration.h"],
    srcs = ["configuration.c"],
)

cc_library(
    name = "config_args",
    hdrs = ["config_args.h"],
)
