cc_library(
    name='exposer',
    include_prefix='iota/utils/exposer',
    hdrs=glob(['*.hpp']),
    srcs=glob(['*.cpp']),
    deps=['@yaml_cpp//:yaml_cpp',],
    visibility=['//visibility:public'])