TRINARY_INT_1_TRITS_PER_WORD_DEFS = [
    "MAM2_TRINARY_WORD_REP_INT",
    "MAM2_TRITS_PER_WORD=1",
]

TRINARY_INTERLEAVED_1_TRITS_PER_WORD_DEFS = [
    "MAM2_TRINARY_WORD_REP_INTERLEAVED",
    "MAM2_TRITS_PER_WORD=1",
]

TRINARY_PACKED_1_TRITS_PER_WORD_DEFS = [
    "MAM2_TRINARY_WORD_REP_PACKED",
    "MAM2_TRITS_PER_WORD=1",
]
