cc_test(
    name = "test_api",
    timeout = "eternal",
    srcs = ["test_api.c"],
    deps = [
        "//common/trinary:tryte_ascii",
        "//mam/api",
        "//mam/mam/tests:test_channel_utils",
        "@unity",
    ],
)
