package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_utils",
    srcs = ["test_utils.c"],
    hdrs = ["test_utils.h"],
    deps = [
        "//mam/v2/mss",
        "//mam/v2/ntru",
        "//mam/v2/ntru:poly",
        "//mam/v2/prng",
        "//mam/v2/sponge",
        "//mam/v2/sponge:spongos",
        "//mam/v2/wots",
    ],
)
