package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pb3",
    srcs = ["pb3.c"],
    hdrs = ["pb3.h"],
    deps = [
        "//common:errors",
        "//mam/v2/sponge:spongos",
    ],
)
