package(default_visibility = ["//visibility:public"])

cc_library(
    name = "concurrent_queue_hash_request",
    hdrs = [
        "concurrent_queue.h.inc",
        "concurrent_queue_hash_request.h",
    ],
    deps = [
        "//common/network:neighbor",
    ],
)

cc_library(
    name = "concurrent_queue_trytes",
    hdrs = [
        "concurrent_queue.h.inc",
        "concurrent_queue_trytes.h",
    ],
    deps = [
        "//common/trinary:tryte",
    ],
)
