package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bundle",
    srcs = ["bundle.c"],
    hdrs = ["bundle.h"],
    deps = [
        "//common:errors",
        "//common/model:bundle",
        "//mam/v2/api",
        "//mam/v2/mam",
    ],
)
