cc_test(
    name = "test_converter",
    timeout = "short",
    srcs = ["test_converter.c"],
    deps = [
        "//common/crypto/kerl:converter",
        "//common/trinary:trit_tryte",
        "@unity",
    ],
)

cc_test(
    name = "test_kerl",
    timeout = "short",
    srcs = ["test_kerl.c"],
    deps = [
        "//common/crypto/kerl",
        "//common/trinary:trit_tryte",
        "@unity",
    ],
)
