package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stdint",
    hdrs = ["stdint.h"],
)

cc_library(
    name = "errors",
    srcs = [
        "errors.c",
        "errors.h",
    ],
    hdrs = ["errors.h"],
)
