cc_test(
    name = "test_merkle",
    srcs = ["test_merkle.c"],
    deps =
        [
            "//common/trinary:trit_tryte",
            "//utils:merkle",
            "@unity",
        ],
)

cc_test(
    name = "test_signed_files",
    srcs = ["test_signed_files.c"],
    deps = [
        "//utils:signed_files",
        "@unity",
    ],
)
