cc_binary(
    name='echocatcher',
    srcs=['echocatcher.cpp'],
    deps=[
        '//utils/common:common',
        '//ccurl:ccurl',
        '//external:cpprestsdk',
        '//external:gflags',
        '//external:glog',
    ])

