cc_binary(
    name='echocatcher',
    srcs=['echocatcher.cpp'],
    deps=[
        '//utils/common:common',
        '//ccurl:ccurl',
        '@cpprestsdk//:cpprestsdk',
        '@com_github_gflags_gflags//:gflags',
        '@glog//:glog',
    ])

