cc_test(
    name = "test_concurrent_queue",
    timeout = "short",
    srcs = ["test_concurrent_queue.c"],
    deps = [
        "//utils/containers/queues:concurrent_queue",
        "@unity",
    ],
)
