load(":hash_set_generator.bzl", "hash_set_generate")

hash_set_generate(size = 27)

hash_set_generate(size = 81)

hash_set_generate(size = 243)

hash_set_generate(size = 6561)

hash_set_generate(size = 8019)
