cc_test(
    name = "test_map",
    srcs = ["test_map.c"],
    deps = [
        "//utils/containers:person_example_t_to_int_map",
        "//utils/containers/hash/tests:defs",
        "@unity",
    ],
)
