cc_library(
    name = "storage",
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//common:logger_helper",
        "//common/trinary:trit_array",
    ],
)
