cc_library(
    name = "spent_addresses",
    srcs = ["spent_addresses.c"],
    hdrs = ["spent_addresses.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//utils:logger_helper",
    ],
)
