cc_test(
    name = "test_checksum",
    timeout = "short",
    srcs = ["test_checksum.c"],
    deps = [
        "//common/helpers:checksum",
        "@unity",
    ],
)

cc_test(
    name = "test_digest",
    timeout = "short",
    srcs = ["test_digest.c"],
    deps = [
        "//common/helpers:digest",
        "@unity",
    ],
)

cc_test(
    name = "test_pow",
    timeout = "short",
    srcs = ["test_pow.c"],
    deps = [
        "//common/helpers:pow",
        "@unity",
    ],
)

cc_test(
    name = "test_sign",
    timeout = "short",
    srcs = ["test_sign.c"],
    deps = [
        "//common/helpers:sign",
        "@unity",
    ],
)
