cc_test(
    name = "test_checksum",
    timeout = "short",
    srcs = ["test_checksum.cpp"],
    deps = [
        "//common/helpers:checksum",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_digest",
    timeout = "short",
    srcs = ["test_digest.cpp"],
    deps = [
        "//common/helpers:digest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_pow",
    timeout = "short",
    srcs = ["test_pow.cpp"],
    deps = [
        "//common/helpers:pow",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_sign",
    timeout = "short",
    srcs = ["test_sign.cpp"],
    deps = [
        "//common/helpers:sign",
        "@com_google_googletest//:gtest_main",
    ],
)
