#include <cstdint>
#include <memory>
#include <iostream>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include "common/helpers/pow.h"

namespace {

std::string TX_TRYTES =
    "XYIUIABLAEBBFCTMDCGPVNCQELHIEBVNRPWBSCABWRAVGVOVMFEHWJCUILYIXOPJNASEOHXPJB"
    "XFNHHSWEKEGEEFSAZDENWMOAXGJCQZQDGSTTMNQPYJBLRVY9T9HSQNXWYCSMLEXVWCASQ9MHPM"
    "BZ9PSSZEKCXYLDYKTOVAWQXOTGMWHUIACLUTAIKUIXZND9YMQKZBTIWOUIVQWTSBNVDCUWYP9H"
    "DMQPTXWEQYXVEOFXVGQSBHGHMKVFZZQIALVLMINZGNLEAOCQZFHPTQTQXGZQJLTBFPLWTESFYO"
    "JNJGJRYWHPEBSPSXEWCITXBJBMXDFCUDUKKGZMDOOPIBJLC9GPIBTLVQWPGTADEXNI9SWJNJXK"
    "XIJCPMICHBIFRXVWNJDP9BDELH9NOMJKGEBOCLWEXPEBFBWQLHFWQVCFIPVUXNREWXTCTFQHZY"
    "TMSUXQZTJQOWZZZCFIJ9NFXVSDFEXLODNJFREDOQ9WLLQAKRYKUCGUYEFICOLCKZHWFCLFGLKO"
    "RFQFZXZXTEXWGRJPZ99KAJYFDWZNMBKQXOLRCAPDZWTZIMSUDSNDTKJLKJWFCTHZFYFW9EF9T9"
    "OGNFBNCRDDTRQUBIBSIWJNRAFXG9UDRGSXDQ9OKAREHQOCXSULYOA9IWJOYGWYOZGVQUDNBZXH"
    "ZBCCBQ9PPKIKSWLNLPRSRRYLGCQIJKYNTAJBGPAOYWIUOIR9WOQYLSQYPWKUWBD9AUVZZT9KWU"
    "NQZYLOKTWRVJDVJSDBO9XYEGJIZWRMU9SRUVGMZUX9BXACUDYNXXRTYN9UVLJUIJGNAHVWSWRF"
    "HKIXTYINVHFHGXJVVJFLFTJR9LPZCJPHQOZQRXFJPYIHCVBXCIXZFPCC9RYLOYMBXDTRDEDWPZ"
    "MZYIKGTXAQYJVEFDSF9QWROXAJS9ZPAWHLKIEKUPFKXOGLUYXCQNVVBYEJG9STYYRHKAOOID9U"
    "DPCMSBOVKWXCTSRSBKOZIIUDAABKXIBIDNTXZWLITYANTGVRYBEOZAOEWGPGLKGICMPADAEHHO"
    "CUSKXBKO9REVSI9FDFDCPMUGCLJVNHMHWHAIURTWDTSHMOPVVMGWLECCPXHAAQRCDCUWDVMBRL"
    "MQYTY9PLIFIUNXZUNY9UIVHBZKMNYOPRSIKBKWDDOYJQWCSPFBLODZVAPGWHJJKOBYETEUUPJD"
    "IFLWUCMYWEUSZLWANGHYSNUXJAPFZJADQWAZCOYXWJAQCYWFBRNXJRHMIUFEROW9Z9QJAPFDIR"
    "UUTD9RPZYFD9PRPU9YVGIQMHNEYVDLEIESZEO9QLOLNHSVNGNZFHODQXXX9K9NAUDG9UENCXFT"
    "S9FQXVXJYIVBL9OPHXTPCWKEDMXXJQLXHBNTNVWHGFNNXAEKGHSBGCQFFIIRKMSYRXBCDTUCJE"
    "SVXJGZTHUJWGWDD9MDXBCXEPBMDZEVUGIXHVCGDFVOYY9QEJJYQALKJWFKMYSKZRXQNGI9MC9F"
    "LSIYER9BZGDXGZUAMBZFJLWNBKMWWOSUE9XGOUPDDSCJWN9PJD9LKUVVYHCRBBBABVKZJOXFGC"
    "RXXDEGLGYDXLFFPWFNCGCRPKGSEXQNONXKJWDGTFZWWOSK9TKUTHGHBNLQADQ9QS9XLNRVUMSR"
    "FVYVSEQEGGTOWHUMZUEVQEROFMYLXYXU9GUJSQFSMMVHQS9SVIH9X9RNORYZOLIIA9RWAUFWDK"
    "QXRAHPALEW9LDXZFSRDCPYVSSXGOEPSVZCVWXDXVJKDWUBGQEUGNAUD9GNEQEVXXLTNVBIWJLL"
    "BCTFZWODFLIIDSNUPDJRHNPH9NBOKOVXCGEEZA9ZWKRNBL9XOOPF9OCP9VORMMVSIASCEAUVVJ"
    "HBLWLHDHWVJDDTEBFIKHOEVIIDJXA9MTLUSZVPJPHLRASOAGNNPQYIAZVKTROQXISIALDESIHL"
    "NREAAPXCFU9AZTORQGYCFWVFHFQMAJPUSYVAEERWGQSKYFZJPWMOAEWXTUEGIDOSSCLBFLMBIZ"
    "HYIQWSCNPZUTTSKCZXDSELK9KSBHTDSUID9LMBMYXQFAWBBRHFKMMBPTFKDNLQSZAMHMYASZXX"
    "KHXKPH9TOHVZUOXDCFHBDNAQEVOQQUGKEW9YQBZWMSVTJGNVUN9TUVYJ9XECFMVIIFTNSNBCUA"
    "9TOHPHAYDSAWJTJANNPZELFSWMVLBRUKJDT9B9VWCXBMUDNLVDEEWQRITLOTFLVOUDQGEEXK9C"
    "O9DCMNDY9VZUGMLVFKLUBNSQOABRDMIWVYGMENSBHUOMGIJ9MNKLST99999999999999999999"
    "9999999999999999999999999999UMJOPYD99A99999999C99999999WUIHHDPDFBHIQLKEFLU"
    "OKIOVFOCPFPWBKUCCGA9YUUEPTLUXRLZHVKEOLJQWHBOLSCWKVXCOBSVJHY9YXDMTFSSWIPNAY"
    "XJPQNQCZAIT9ADYOLDXZVBTEUWMVYOOODSCPKAWWHOFQTLZKRPURYBMCU9YHSIYQZ9999W9VEL"
    "HQPPERYSG9ZLLAHQKDLJQBKYYZOSRQOESEELED9CZHBLAMALTJJZAFWNMWGAAUFJMNQDGKVA99"
    "99999999999999999999999999999HDU9RGVJE999999999MMMMMMMMMDC99999999OKGA9999"
    "999999999";

TEST(PoWTest, testsPoW) {
  using namespace testing;
  auto nonce = iota_pow(TX_TRYTES.c_str(), 9);

  //FIXME(th0br0) verify that nonce yields a good hash

  //std::cerr << "TX: " << TX_TRYTES << std::endl;
  //std::cerr << "Nonce: " << nonce << std::endl;
  std::free(nonce);
  
}

}  // namespace
