cc_library(
    name = "ledger_validator",
    srcs = ["ledger_validator.c"],
    hdrs = ["ledger_validator.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//utils:logger_helper",
    ],
)
