cc_test(
    name = "test_iss_curl",
    timeout = "short",
    srcs = [
        "test_iss_curl.c",
    ],
    deps = [
        "//common/crypto/curl-p:trit",
        "//common/crypto/iss/v2:iss_curl",
        "//common/trinary:trit_tryte",
        "@unity",
    ],
)
