cc_test(
    name = "test_sponge",
    timeout = "short",
    srcs = ["test_sponge.c"],
    deps = [
        "//common/crypto/sponge",
        "//common/model:transaction",
        "@unity",
    ],
)
