#!/bin/bash

/etc/init.d/mysql start
mysql -u root < common/storage/sql/mariadb/setup.sql
mysql -u ciri tangle < common/storage/sql/mariadb/tangle-schema.sql
mysql -u ciri spent-addresses < common/storage/sql/mariadb/spent-addresses-schema.sql
