#!/bin/bash

/etc/init.d/mysql start
mysql -u root < ciri/storage/sql/mariadb/setup.sql
mysql -u ciri tangle < ciri/storage/sql/mariadb/tangle-schema.sql
mysql -u ciri spent-addresses < ciri/storage/sql/mariadb/spent-addresses-schema.sql
