#!/bin/sh

root=$(git rev-parse --show-toplevel)
python $root/tools/cpplint.py --linelength=120 --filter=-build/include_order,-whitespace/comments,-runtime/references --extensions=h,cc $(find $root/cppclient | grep -E "\.(cc|cpp|h|hh|hpp)\$")
