#!/bin/bash

status=0
for file in $(git diff --staged --name-only | grep -E "\.(c|cc|cpp|h|hh|hpp)\$")
do
  output=$(diff <(cat $file) <(clang-format -style=file -fallback-style=none $file))
  if [ $? -ne 0 ]
  then
    echo -e "\nFile \""$file"\" is not compliant with the coding style"
    echo "$output"
    status=1
  fi
done
exit $status
