cc_test(
    name = "test_entry_point_selector",
    srcs = ["test_entry_point_selector.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//consensus/entry_point_selector",
        "@unity",
    ],
)
