cxx_binary(
    name='statscollector',
    srcs=['statscollector.cpp'],
    compiler_flags=['-std=c++17'],
    deps=[
        '//utils/common:common',
        '//third-party/google/gflags:gflags',
        '//third-party/google/glog:glog',
        '//third-party/influxdb-cpp-rest:influxdb-cpp',
    ])

