cc_library(
    name = "defs",
    srcs = ["defs.c"],
    hdrs = ["defs.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:errors",
        "//common/storage/sql/sqlite3:sqlite3_storage",
        "//consensus/tangle",
        "//utils:files",
    ],
)
