cc_test (
    name = "test_ptrit",
    srcs = ["test_trit_ptrit.c"],
    deps = [
        "//common/trinary:trit_ptrit",
        "@unity//:unity",
        ]
)
cc_test (
    name = "test_byte",
    srcs = ["test_trit_byte.c"],
    deps = [
        "//common/trinary:trit_byte",
        "@unity//:unity",
        ]
)
cc_test (
    name = "test_tryte",
    srcs = ["test_trit_tryte.c"],
    deps = [
        "//common/trinary:trit_tryte",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_long",
    srcs = ["test_trit_long.c"],
    deps = [
        "//common/trinary:trit_long",
        "@unity//:unity",
        ]
)

cc_test (
    name = "test_tryte_long",
    srcs = ["test_tryte_long.c"],
    deps = [
        "//common/trinary:tryte_long",
        "@unity//:unity",
    ]
)

cc_test (
    name = "test_add",
    srcs = ["test_add.c"],
    deps = [
        "//common/trinary:add",
        "@unity//:unity",
    ]
)

cc_test (
    name = "test_trit_array",
    srcs = ["test_trit_array.c"],
    deps = [
        "//common/trinary:trit_array",
        "//common/trinary:trit_byte",
        "@unity//:unity",
    ]
)