cc_library(
    name = "types",
    hdrs = [
        "types.h",
    ],
    include_prefix = "types",
    visibility = ["//visibility:public"],
    deps = [
        "//common/trinary:trit_array_1",
        "//common/trinary:tryte",
    ],
)
